name: Repository
  
on: 
  issues:
    types:
      - opened
      - edited
      
jobs: 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Creating a repo from Template
      if: contains(github.event.issue.labels.*.name, 'policies')
      run: | 
         echo "Testing Issue body"
         echo "issue=$(curl \
         -H "Accept: application/vnd.github.v3+json" \
         https://api.github.com/repos/Punith0480/Issue_test/issues/10)" >> $GITHUB_ENV
    - name: testing vaariable
      run: |
         echo "${{ fromJSON(env.issue) }}"
